### PR TITLE
Protect bash-special characters in filenames

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. I've seen a similar change before, but I'm still not clear on what kind of error this prevents.  Can you give an example?

**Comment by DamienCassou** [comment]
If you have a filename with a space for example, the old version would pass 2 halves of a filename as 2 separate arguments to ffmpeg.

**Comment by DamienCassou** [comment]
On March 13, 2017 12:09:29 PM GMT+01:00, Oleh Krehel <notifications@github.com> wrote:
>> If you have a filename with a space for example
>
>This is already handled by the Elisp layer:
>
>- `" "` are transformed to `"α"` (and in reverse with `mis-finalize`)
>- `":"` are transformed to `"β"`
>
>If you know of other (typical) chars that cause problems, let me know.

My filenames also had quotes and parentheses. Why do you transform filenames instead of protecting?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by abo-abo** [comment]
> Why do you transform filenames instead of protecting?

Seemed simpler at the time. I'd like to avoid putting too much repetitive logic in the Makefiles.

**Comment by DamienCassou** [comment]
I disagree :-). I think it's simpler to protect file names with quotes than to rewrite names. First, rewriting might miss some protected characters (as is the case here). Second, you prevent people from using the special characters your code use such as α and β in their file names I guess.

**Pull request merged**
