### PR TITLE
add mixed extensions convert and mix recipes

### PR DESCRIPTION
**Pull request by sukeyisme**
may be useful

### CODE REVIEW

**Comment by abo-abo** [comment]
I don't understand what your Elisp change tries to achieve.

In any case, it breaks `recipes/cue/split/Makefile`. The idea with this recipe is that, although the file extensions are mixed, the file under cursor is "main", thus `*.cue` has a `split` action and `*.flac` doesn't. Maybe you could use the same concept for your `enca` recipe.

**Comment by sukeyisme** [comment]
Such as I want to put all the files in a project from a code into another kind of code, but the files and documents suffixes are unchanged, if to create a recipe based on the document file suffix, may have different suffix files in the project lead to need to create multiple recipe. I will have look what you say. thanks.

**Comment by sukeyisme** [comment]
Should I understand what you said, every time for the whole project transcoding all need to let the cursor on the file with the suffix, so that you can not create multiple recipes

**Comment by abo-abo** [comment]
You can now run `make-it-so` with a prefix arg `2` to run it on a mix of files.

Have a look at `recipes/mix/enca/Makefile`. I have edited it heavily from your initial version.

The new change is that <kbd>2,</kbd> will append each file with the `mix` suffix. And the convention is to transform `mix` to `out`.

**Comment by sukeyisme** [comment]
But there is a problem, after "mis-replace" the file suffix will be ".out" which is not the original. Encoding convert should not change the suffix.

**Pull request closed without merging**
